import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [count, setCount] = useState(0);

  console.log(1);

  useEffect(() => {
    console.log("component mount");
    console.log("component did update");
    return () => {
      console.log("component did unmount");
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Balance App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#02096d] to-[#15262c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 text-white">
          test1
        </div>
      </main>
    </>
  );
};

export default Home;
